'use strict';

const onJoin = require('../common').generatePerChanListManagementUCExport('onJoin');

if (!onJoin.__drcHelp) {
  onJoin.__drcHelp = () => ({
    title: 'Manage actions to perform when users join a channel',
    usage: 'network #channel_id subcommand [action]',
    notes: 'Maintains a list of actions to be performed when users join the specified channel. Generated by the listManagementUCGenerators utility.',
    subcommands: {
      add: {
        text: 'Add an action to the list'
      },
      remove: {
        text: 'Remove an action from the list'
      },
      clear: {
        text: 'Clear all actions from the list'
      }
    }
  });
}

module.exports = onJoin;
