'use strict';

const showPerChan = require('../common').generatePerChanListManagementUCExport('showPerChan');

if (!showPerChan.__drcHelp) {
  showPerChan.__drcHelp = () => ({
    title: 'Manage a per-channel list of strings',
    usage: 'network #channel_id subcommand [string]',
    notes: 'Maintains a list of strings for specific channels. Generated by the listManagementUCGenerators utility.',
    subcommands: {
      add: {
        text: 'Add a string to the list'
      },
      remove: {
        text: 'Remove a string from the list'
      },
      clear: {
        text: 'Clear all strings from the list'
      }
    }
  });
}

module.exports = showPerChan;
